# Welcome to Jekyll!

# Site settings
title: My blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    My simple blog about tech and etc

github_username:  storytime
linkedin_username: bogdan-fedorchenko-86228071

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-104486159-1
disqus_shortname: https-storytime-github-io-pages

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
